<a href="https://colab.research.google.com/github/hanene2030/pandas/blob/main/1_loading_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loading data

In [25]:
import numpy as np
import pandas as pd
import pickle
filename = "heart.csv"

# The best method - pandas read_csv


In [26]:
df = pd.read_csv(filename)
df.head(3)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1

# Using numpy's loadtxt and genfromtxt

In [29]:
data = np.loadtxt(filename , delimiter=",", skiprows=1)
print(data)

[[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [31]:
data = np.genfromtxt(filename , delimiter=",", dtype=None, names=True , encoding="utf-8-sig"  )
print( data.dtype)
print(data)

[('age', '<i8'), ('sex', '<i8'), ('cp', '<i8'), ('trestbps', '<i8'), ('chol', '<i8'), ('fbs', '<i8'), ('restecg', '<i8'), ('thalach', '<i8'), ('exang', '<i8'), ('oldpeak', '<f8'), ('slope', '<i8'), ('ca', '<i8'), ('thal', '<i8'), ('target', '<i8')]
[(63, 1, 3, 145, 233, 1, 0, 150, 0, 2.3, 0, 0, 1, 1)
 (37, 1, 2, 130, 250, 0, 1, 187, 0, 3.5, 0, 0, 2, 1)
 (41, 0, 1, 130, 204, 0, 0, 172, 0, 1.4, 2, 0, 2, 1)
 (56, 1, 1, 120, 236, 0, 1, 178, 0, 0.8, 2, 0, 2, 1)
 (57, 0, 0, 120, 354, 0, 1, 163, 1, 0.6, 2, 0, 2, 1)
 (57, 1, 0, 140, 192, 0, 1, 148, 0, 0.4, 1, 0, 1, 1)
 (56, 0, 1, 140, 294, 0, 0, 153, 0, 1.3, 1, 0, 2, 1)
 (44, 1, 1, 120, 263, 0, 1, 173, 0, 0. , 2, 0, 3, 1)
 (52, 1, 2, 172, 199, 1, 1, 162, 0, 0.5, 2, 0, 3, 1)
 (57, 1, 2, 150, 168, 0, 1, 174, 0, 1.6, 2, 0, 2, 1)
 (54, 1, 0, 140, 239, 0, 1, 160, 0, 1.2, 2, 0, 2, 1)
 (48, 0, 2, 130, 275, 0, 1, 139, 0, 0.2, 2, 0, 2, 1)
 (49, 1, 1, 130, 266, 0, 1, 171, 0, 0.6, 2, 0, 2, 1)
 (64, 1, 3, 110, 211, 0, 0, 144, 1, 1.8, 1, 0, 2, 1)
 (58, 0, 

# Manual loading
### For completly weird file structure 

In [33]:
def load_file(filename):
  with open(filename, encoding="utf-8-sig") as f:
    data,cols=[],[]
    for i,line in enumerate(f.read().splitlines()):
      if i == 0:
        cols += line.split(",")
      else:
        data.append([float(x) for x in line.split(',')])
    df = pd.DataFrame(data, columns=cols)
  return df

load_file(filename).head(3)


age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  3.0     145.0  233.0  1.0      0.0    150.0    0.0      2.3   
1  37.0  1.0  2.0     130.0  250.0  0.0      1.0    187.0    0.0      3.5   
2  41.0  0.0  1.0     130.0  204.0  0.0      0.0    172.0    0.0      1.4   

   slope   ca  thal  target  
0    0.0  0.0   1.0     1.0  
1    0.0  0.0   2.0     1.0  
2    2.0  0.0   2.0     1.0

# Pickles

In [34]:
df = pd.read_pickle("heart.pkl")

In [35]:
df.head(3)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1

In [36]:
df.to_csv("heart_from_pkl.csv")