<a href="https://colab.research.google.com/github/hanene2030/pandas/blob/main/2_pandas_vs_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas vs numpy

1. Pandas has a numpy core
2. They do present different data structures

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("heart.csv")
df.head(2)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   

   ca  thal  target  
0   0     1       1  
1   0     2       1

In [2]:
data = df.to_numpy()


In [3]:
print(data.dtype,data) # First thing to note, the data type is float 64. numpy converted our entire array to a single type floats 


float64 [[63.  1.  3. ...  0.  1.  1.]
 [37.  1.  2. ...  0.  2.  1.]
 [41.  0.  1. ...  0.  2.  1.]
 ...
 [68.  1.  0. ...  2.  3.  0.]
 [57.  1.  0. ...  1.  3.  0.]
 [57.  0.  1. ...  1.  2.  0.]]


In [4]:
data[0,0] =100
data, df.head(2) # the numpy data has changed, but the original panda's data frame not

(array([[100.,   1.,   3., ...,   0.,   1.,   1.],
        [ 37.,   1.,   2., ...,   0.,   2.,   1.],
        [ 41.,   0.,   1., ...,   0.,   2.,   1.],
        ...,
        [ 68.,   1.,   0., ...,   2.,   3.,   0.],
        [ 57.,   1.,   0., ...,   1.,   3.,   0.],
        [ 57.,   0.,   1., ...,   1.,   2.,   0.]]),
    age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
 0   63    1   3       145   233    1        0      150      0      2.3      0   
 1   37    1   2       130   250    0        1      187      0      3.5      0   
 
    ca  thal  target  
 0   0     1       1  
 1   0     2       1  )

In [5]:
df2 = df[["age","sex","cp"]]
data2 =  df2.to_numpy()
data2[0,0] =100
df2.head(2) 
# just be aware that even if you're working with a non-pandas object,still very likely be modifying the panda's

age  sex  cp
0  100    1   3
1   37    1   2

In [6]:
df3 = df[["age","sex","cp"]]
#data3 =  df3.to_numpy(copy=True)
data3 =  df3.to_numpy().copy()
data3[0,0] =100
df3.head(2) 

age  sex  cp
0   63    1   3
1   37    1   2

In [7]:
df.age.to_numpy()[0]=20
df.head(2)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   20    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   

   ca  thal  target  
0   0     1       1  
1   0     2       1

In [8]:
print(df['age'].mean(),df['age'].to_numpy().mean())

54.224422442244226 54.224422442244226


In [13]:
#pandas doesn't have a reshape funct
df['age'].to_numpy().reshape(3,-1)

array([[20, 37, 41, 56, 57, 57, 56, 44, 52, 57, 54, 48, 49, 64, 58, 50,
        58, 66, 43, 69, 59, 44, 42, 61, 40, 71, 59, 51, 65, 53, 41, 65,
        44, 54, 51, 46, 54, 54, 65, 65, 51, 48, 45, 53, 39, 52, 44, 47,
        53, 53, 51, 66, 62, 44, 63, 52, 48, 45, 34, 57, 71, 54, 52, 41,
        58, 35, 51, 45, 44, 62, 54, 51, 29, 51, 43, 55, 51, 59, 52, 58,
        41, 45, 60, 52, 42, 67, 68, 46, 54, 58, 48, 57, 52, 54, 45, 53,
        62, 52, 43, 53, 42],
       [59, 63, 42, 50, 68, 69, 45, 50, 50, 64, 57, 64, 43, 55, 37, 41,
        56, 46, 46, 64, 59, 41, 54, 39, 34, 47, 67, 52, 74, 54, 49, 42,
        41, 41, 49, 60, 62, 57, 64, 51, 43, 42, 67, 76, 70, 44, 60, 44,
        42, 66, 71, 64, 66, 39, 58, 47, 35, 58, 56, 56, 55, 41, 38, 38,
        67, 67, 62, 63, 53, 56, 48, 58, 58, 60, 40, 60, 64, 43, 57, 55,
        65, 61, 58, 50, 44, 60, 54, 50, 41, 51, 58, 54, 60, 60, 59, 46,
        67, 62, 65, 44, 60],
       [58, 68, 62, 52, 59, 60, 49, 59, 57, 61, 39, 61, 56, 43, 62, 63,
      

In [14]:
#numpy doesnt have a quantile fnct
print(df['age'].quantile())

55.0
