<a href="https://colab.research.google.com/github/hanene2030/pandas/blob/main/3_creating_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating dataframes

In [4]:
import pandas as pd
import numpy as np
data = np.random.random(size=(6,4))
df = pd.DataFrame(data=data,columns=["A","B","C","D"])
print(data)
df

[[0.96418306 0.9080051  0.9809547  0.41764831]
 [0.65029318 0.54514645 0.77071619 0.46231404]
 [0.20711178 0.93531365 0.21245588 0.51419139]
 [0.39145504 0.14745901 0.64951882 0.63745851]
 [0.1118594  0.21252651 0.06564266 0.20544697]
 [0.8922695  0.46834088 0.9596309  0.38113313]]


A         B         C         D
0  0.964183  0.908005  0.980955  0.417648
1  0.650293  0.545146  0.770716  0.462314
2  0.207112  0.935314  0.212456  0.514191
3  0.391455  0.147459  0.649519  0.637459
4  0.111859  0.212527  0.065643  0.205447
5  0.892270  0.468341  0.959631  0.381133

In [3]:
df = pd.DataFrame(data={"A":[1,2,3],"B":["Alex","Jean","Emma"]})
df


A     B
0  1  Alex
1  2  Jean
2  3  Emma

In [8]:
dtype = [("A", np.int_), ("B", (np.str_,20))]
data = np.array([(1,"Jean"),(2,"Alex"),(3,"Seb")],dtype=dtype)
df = pd.DataFrame(data)
df

A     B
0  1  Jean
1  2  Alex
2  3   Seb

In [10]:
data = [{"A": 1, "B":"Jean"}, {"A": 2, "B":"Alex"},{"A": 3, "B":"SEb"}]
df = pd.DataFrame(data)
df

A     B
0  1  Jean
1  2  Alex
2  3   SEb